[build]
  command   = "npm run build"
  functions = "out_functions"
  publish   = "out_publish"
[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=604800"
