export default {
  cms_manual_init: true,
  backend: {
    name: 'git-gateway',
    branch: 'master',
    identity_url: 'https://agitated-swanson-98b631.netlify.app/.netlify/identity',
    gateway_url: 'https://agitated-swanson-98b631.netlify.app/.netlify/git',
  },
  media_folder: 'public/assets/img',
  public_folder: '/assets/img',
  slug: {
    encoding: 'ascii',
    clean_accents: true,
  },
  collections: [
    {
      name: 'pages',
      label: 'Strony',
      files: [
        {
          name: 'home',
          label: 'Strona główna',
          file: 'content/pages/home.md',
          fields: [
            {
              name: 'pageTitle',
              label: 'Tytuł strony głównej',
              widget: 'string',
              required: true,
            },
            {
              name: 'pageDescription',
              label: 'Opis strony głównej',
              widget: 'string',
              required: true,
            },
          ],
        },
        {
          name: 'articles',
          label: 'Artykuły',
          file: 'content/pages/articles.md',
          fields: [
            {
              name: 'pageTitle',
              label: 'Tytuł podstrony artykułów',
              widget: 'string',
              required: true,
            },
            {
              name: 'pageDescription',
              label: 'Opis podstrony artykułów',
              widget: 'string',
              required: true,
            },
          ],
        },
        {
          name: 'tips',
          label: 'Porady',
          file: 'content/pages/tips.md',
          fields: [
            {
              name: 'pageTitle',
              label: 'Tytuł podstrony artykułów',
              widget: 'string',
              required: true,
            },
            {
              name: 'pageDescription',
              label: 'Opis podstrony artykułów',
              widget: 'string',
              required: true,
            },
          ],
        },
        {
          name: 'ads',
          label: 'Ogłoszenia',
          file: 'content/pages/ads.md',
          fields: [
            {
              name: 'pageTitle',
              label: 'Tytuł podstrony artykułów',
              widget: 'string',
              required: true,
            },
            {
              name: 'pageDescription',
              label: 'Opis podstrony artykułów',
              widget: 'string',
              required: true,
            },
          ],
        },
        {
          name: 'contact',
          label: 'Kontakt',
          file: 'content/pages/contact.md',
          fields: [
            {
              name: 'pageTitle',
              label: 'Tytuł podstrony artykułów',
              widget: 'string',
              required: true,
            },
            {
              name: 'pageDescription',
              label: 'Opis podstrony artykułów',
              widget: 'string',
              required: true,
            },
            {
              name: 'contactEmail',
              label: 'Email kontaktowy',
              widget: 'string',
              required: true,
            },
            {
              name: 'facebookUrl',
              label: 'Adres profilu na facebooku',
              widget: 'string',
              required: true,
            },
            {
              name: 'twitterUrl',
              label: 'Adres profilu na twitterze',
              widget: 'string',
              required: true,
            },
            {
              name: 'instagramUrl',
              label: 'Adres profilu na instagramie',
              widget: 'string',
              required: true,
            },
          ],
        },
      ],
    },
    {
      name: 'category-articles',
      label: 'Kategorie artykułów',
      folder: 'content/categories/articles',
      create: true,
      fields: [
        {
          name: 'title',
          label: 'Nazwa kategorii dla artykułów',
          widget: 'string',
          required: true,
        },
        {
          name: 'pageTitle',
          label: 'Tytuł podstrony dla kategorii artykułów',
          widget: 'string',
          required: true,
        },
        {
          name: 'pageDescription',
          label: 'Opis podstrony dla kategorii artykułów',
          widget: 'string',
          required: true,
        },
        {
          name: 'icon',
          label: 'Ikona kategorii',
          widget: 'string',
          required: true,
        },
      ],
    },
    {
      name: 'category-tips',
      label: 'Kategorie porad',
      folder: 'content/categories/tips',
      create: true,
      fields: [
        {
          name: 'title',
          label: 'Nazwa kategorii dla porad',
          widget: 'string',
          required: true,
        },
        {
          name: 'pageTitle',
          label: 'Tytuł podstrony dla kategorii porad',
          widget: 'string',
          required: true,
        },
        {
          name: 'pageDescription',
          label: 'Opis podstrony dla kategorii porad',
          widget: 'string',
          required: true,
        },
        {
          name: 'icon',
          label: 'Ikona kategorii',
          widget: 'string',
          required: true,
        },
      ],
    },
    {
      name: 'category-contact',
      label: 'Kategorie kontakt',
      folder: 'content/categories/contact',
      create: true,
      fields: [
        {
          name: 'title',
          label: 'Nazwa kategorii',
          widget: 'string',
          required: true,
        },
        {
          name: 'position',
          label: 'Pozycja na liście',
          widget: 'number',
          required: true,
        },
      ],
    },
    {
      name: 'articles',
      label: 'Artykuły',
      folder: 'content/posts/articles',
      create: true,
      fields: [
        {
          name: 'pageTitle',
          label: 'Tytuł podstrony',
          widget: 'string',
          required: true,
        },
        {
          name: 'pageDescription',
          label: 'Opis podstrony',
          widget: 'string',
          required: true,
        },
        {
          name: 'title',
          label: 'Tytuł artykułu',
          widget: 'string',
          required: true,
        },
        {
          name: 'subtitle',
          label: 'Podtytuł artykułu',
          widget: 'string',
          required: true,
        },
        {
          name: 'date',
          label: 'Data publikacji',
          widget: 'datetime',
          required: true,
        },
        {
          name: 'featuredImage',
          label: 'Obraz',
          widget: 'image',
          required: true,
          allow_multiple: false,
        },
        {
          name: 'imageSource',
          label: 'Źródło obrazka',
          widget: 'string',
        },
        {
          name: 'category',
          label: 'Kategorie',
          widget: 'relation',
          collection: 'category-articles',
          searchFields: ['title'],
          valueField: 'title',
          required: true,
        },
        {
          name: 'contents',
          label: 'Spis treści',
          widget: 'list',
          fields: [
            {
              name: 'name',
              label: 'Nazwa',
              widget: 'string',
              required: true,
            },
            {
              name: 'link',
              label: 'Odnośnik',
              widget: 'string',
              required: true,
            },
          ],
        },
        {
          name: 'gallery',
          label: 'Zdjęcia w galerii',
          widget: 'list',
          fields: [
            {
              name: 'image',
              label: 'Zdjęcie',
              widget: 'image',
              required: true,
            },
            {
              name: 'alt',
              label: 'Alt zdjęcia',
              widget: 'string',
              required: true,
            },
            {
              name: 'source',
              label: 'Źródło zdjęcia',
              widget: 'string',
            },
          ],
        },
        {
          name: 'highlightedText',
          label: 'Wyróżniony nagłówek',
          widget: 'markdown',
          required: true,
        },
        {
          name: 'text',
          label: 'Treść',
          widget: 'markdown',
          required: true,
        },
      ],
    },
    {
      name: 'tips',
      label: 'Porady',
      folder: 'content/posts/tips',
      create: true,
      fields: [
        {
          name: 'pageTitle',
          label: 'Tytuł podstrony',
          widget: 'string',
          required: true,
        },
        {
          name: 'pageDescription',
          label: 'Opis podstrony',
          widget: 'string',
          required: true,
        },
        {
          name: 'title',
          label: 'Tytuł porady',
          widget: 'string',
          required: true,
        },
        {
          name: 'subtitle',
          label: 'Podtytuł porady',
          widget: 'string',
          required: true,
        },
        {
          name: 'date',
          label: 'Data publikacji',
          widget: 'datetime',
          required: true,
        },
        {
          name: 'featuredImage',
          label: 'Obraz',
          widget: 'image',
          required: true,
          allowMultiple: false,
        },
        {
          name: 'imageSource',
          label: 'Źródło obrazka',
          widget: 'string',
        },
        {
          name: 'category',
          label: 'Kategorie',
          widget: 'relation',
          collection: 'category-tips',
          searchFields: ['title'],
          valueField: 'title',
        },
        {
          name: 'contents',
          label: 'Spis treści',
          widget: 'list',
          fields: [
            {
              name: 'name',
              label: 'Nazwa',
              widget: 'string',
              required: true,
            },
            {
              name: 'link',
              label: 'Odnośnik',
              widget: 'string',
              required: true,
            },
          ],
        },
        {
          name: 'gallery',
          label: 'Zdjęcia w galerii',
          widget: 'list',
          fields: [
            {
              name: 'image',
              label: 'Zdjęcie',
              widget: 'image',
              required: true,
            },
            {
              name: 'alt',
              label: 'Alt zdjęcia',
              widget: 'string',
              required: true,
            },
            {
              name: 'source',
              label: 'Źródło zdjęcia',
              widget: 'string',
            },
          ],
        },
        {
          name: 'highlightedText',
          label: 'Wyróżniony nagłówek',
          widget: 'markdown',
          required: true,
        },
        {
          name: 'text',
          label: 'Treść',
          widget: 'markdown',
          required: true,
        },
      ],
    },
    {
      name: 'ads',
      label: 'Ogłoszenia',
      folder: 'content/posts/ads',
      create: true,
      fields: [
        {
          name: 'pageTitle',
          label: 'Tytuł podstrony',
          widget: 'string',
          required: true,
        },
        {
          name: 'pageDescription',
          label: 'Opis podstrony',
          widget: 'string',
          required: true,
        },
        {
          name: 'title',
          label: 'Tytuł ogłoszenia',
          widget: 'string',
          required: true,
        },
        {
          name: 'subtitle',
          label: 'Podtytuł ogłoszenia',
          widget: 'string',
          required: true,
        },
        {
          name: 'date',
          label: 'Data publikacji',
          widget: 'datetime',
          required: true,
        },
        {
          name: 'featuredImage',
          label: 'Obraz',
          widget: 'image',
          required: true,
          allowMultiple: false,
        },
        {
          name: 'imageSource',
          label: 'Źródło obrazka',
          widget: 'string',
        },
        {
          name: 'carData',
          label: 'Dane pojazdu',
          widget: 'object',
          fields: [
            {
              name: 'name',
              label: 'Nazwa',
              widget: 'string',
              required: true,
            },
            {
              name: 'localization',
              label: 'Miasto',
              widget: 'string',
              required: true,
            },
            {
              name: 'year',
              label: 'Rok produkcji',
              widget: 'number',
              required: true,
            },
            {
              name: 'body',
              label: 'Nadwozie',
              widget: 'string',
              required: true,
            },
            {
              name: 'engine',
              label: 'Silnik',
              widget: 'string',
              required: true,
            },
            {
              name: 'gearbox',
              label: 'Skrzynia biegów',
              widget: 'string',
              required: true,
            },
            {
              name: 'hp',
              label: 'Ilość koni mechanicznych',
              widget: 'number',
              required: true,
            },
            {
              name: 'torque',
              label: 'Moment obrotowy',
              widget: 'number',
              required: true,
            },
            {
              name: 'doors',
              label: 'Ilość drzwi',
              widget: 'number',
              required: true,
            },
            {
              name: 'course',
              label: 'Przebieg',
              widget: 'number',
              required: true,
            },
            {
              name: 'price',
              label: 'Cena',
              widget: 'string',
              required: true,
            },
          ],
        },
        {
          name: 'contents',
          label: 'Spis treści',
          widget: 'list',
          fields: [
            {
              name: 'name',
              label: 'Nazwa',
              widget: 'string',
              required: true,
            },
            {
              name: 'link',
              label: 'Odnośnik',
              widget: 'string',
              required: true,
            },
          ],
        },
        {
          name: 'gallery',
          label: 'Zdjęcia w galerii',
          widget: 'list',
          fields: [
            {
              name: 'image',
              label: 'Zdjęcie',
              widget: 'image',
              required: true,
            },
            {
              name: 'alt',
              label: 'Alt zdjęcia',
              widget: 'string',
              required: true,
            },
            {
              name: 'source',
              label: 'Źródło zdjęcia',
              widget: 'string',
            },
          ],
        },
        {
          name: 'highlightedText',
          label: 'Wyróżniony nagłówek',
          widget: 'markdown',
          required: true,
        },
        {
          name: 'text',
          label: 'Treść',
          widget: 'markdown',
          required: true,
        },
      ],
    },
    {
      name: 'settings',
      label: 'Ustawienia',
      files: [
        {
          name: 'contact',
          label: 'Kontakt',
          file: 'content/settings/contact.md',
          fields: [
            {
              name: 'contactEmail',
              label: 'Email kontaktowy',
              widget: 'string',
              required: true,
            },
          ],
        },
        {
          name: 'socials',
          label: 'Social media',
          file: 'content/settings/socials.md',
          fields: [
            {
              name: 'facebookUrl',
              label: 'Facebook',
              widget: 'string',
              required: true,
            },
            {
              name: 'instagramUrl',
              label: 'Instagram',
              widget: 'string',
              required: true,
            },
            {
              name: 'twitterUrl',
              label: 'Twitter',
              widget: 'string',
              required: true,
            },
          ],
        },
      ],
    },
  ],
};
