backend:
  name: git-gateway
  branch: master
media_folder: public/assets/img
public_folder: /assets/img
slug:
  encoding: 'ascii'
  clean_accents: true
collections:
  - name: 'pages'
    label: 'Strony'
    files:
      - name: 'home'
        label: 'Strona główna'
        file: 'content/pages/home.md'
        fields:
          - { label: 'Tytuł strony głównej', name: 'pageTitle', widget: 'string', required: true }
          - {
              label: 'Opis strony głównej',
              name: 'pageDescription',
              widget: 'string',
              required: true,
            }
      - name: 'articles'
        label: 'Artykuły'
        file: 'content/pages/articles.md'
        fields:
          - {
              label: 'Tytuł podstrony artykułów',
              name: 'pageTitle',
              widget: 'string',
              required: true,
            }
          - {
              label: 'Opis podstrony artykułów',
              name: 'pageDescription',
              widget: 'string',
              required: true,
            }
      - name: 'tips'
        label: 'Porady'
        file: 'content/pages/tips.md'
        fields:
          - {
              label: 'Tytuł podstrony artykułów',
              name: 'pageTitle',
              widget: 'string',
              required: true,
            }
          - {
              label: 'Opis podstrony artykułów',
              name: 'pageDescription',
              widget: 'string',
              required: true,
            }
      - name: 'ads'
        label: 'Ogłoszenia'
        file: 'content/pages/ads.md'
        fields:
          - {
              label: 'Tytuł podstrony artykułów',
              name: 'pageTitle',
              widget: 'string',
              required: true,
            }
          - {
              label: 'Opis podstrony artykułów',
              name: 'pageDescription',
              widget: 'string',
              required: true,
            }
      - name: 'contact'
        label: 'Kontakt'
        file: 'content/pages/contact.md'
        fields:
          - {
              label: 'Tytuł podstrony artykułów',
              name: 'pageTitle',
              widget: 'string',
              required: true,
            }
          - {
              label: 'Opis podstrony artykułów',
              name: 'pageDescription',
              widget: 'string',
              required: true,
            }
          - { label: 'Email kontaktowy', name: 'contactEmail', widget: 'string', required: true }
          - {
              label: 'Adres profilu na facebooku',
              name: 'facebookUrl',
              widget: 'string',
              required: true,
            }
          - {
              label: 'Adres profilu na twitterze',
              name: 'twitterUrl',
              widget: 'string',
              required: true,
            }
          - {
              label: 'Adres profilu na instagramie',
              name: 'instagramUrl',
              widget: 'string',
              required: true,
            }
  - name: 'category-articles'
    label: 'Kategorie artykułów'
    folder: 'content/categories/articles'
    create: true
    fields:
      - { label: 'Nazwa kategorii dla artykułów', name: 'title', widget: 'string', required: true }
      - {
          label: 'Tytuł podstrony dla kategorii artykułów',
          name: 'pageTitle',
          widget: 'string',
          required: true,
        }
      - {
          label: 'Opis podstrony dla kategorii artykułów',
          name: 'pageDescription',
          widget: 'string',
          required: true,
        }
      - { label: 'Ikona kategorii', name: 'icon', widget: 'string', required: true }
  - name: 'category-tips'
    label: 'Kategorie porad'
    folder: 'content/categories/tips'
    create: true
    fields:
      - { label: 'Nazwa kategorii dla porad', name: 'title', widget: 'string', required: true }
      - {
          label: 'Tytuł podstrony dla kategorii porad',
          name: 'pageTitle',
          widget: 'string',
          required: true,
        }
      - {
          label: 'Opis podstrony dla kategorii porad',
          name: 'pageDescription',
          widget: 'string',
          required: true,
        }
      - { label: 'Ikona kategorii', name: 'icon', widget: 'string', required: true }
  - name: 'articles'
    label: 'Artykuły'
    folder: 'content/posts/articles'
    create: true
    fields:
      - { label: 'Tytuł podstrony', name: 'pageTitle', widget: 'string', required: true }
      - { label: 'Opis podstrony', name: 'pageDescription', widget: 'string', required: true }
      - { label: 'Tytuł artykułu', name: 'title', widget: 'string', required: true }
      - { label: 'Podtytuł artykułu', name: 'subtitle', widget: 'string', required: true }
      - { label: 'Data publikacji', name: 'date', widget: 'datetime', required: true }
      - {
          label: 'Obraz',
          name: 'featuredImage',
          widget: 'image',
          required: true,
          allow_multiple: false,
        }
      - {
          label: 'Kategorie',
          name: 'category',
          widget: 'relation',
          collection: 'category-articles',
          searchFields: ['title'],
          valueField: 'title',
          required: true,
        }
      - label: 'Spis treści'
        name: 'contents'
        widget: 'list'
        fields:
          - { label: 'Nazwa', name: 'name', widget: 'string', required: true }
          - { label: 'Odnośnik', name: 'link', widget: 'string', required: true }
      - label: 'Galeria zdjęć', 
        name: 'gallery', 
        widget: 'image', 
        allow_multiple: true, 
        media_library: 
          config:
            multiple: true 
      - {
          label: 'Wyróżniony nagłówek',
          name: 'highlightedText',
          widget: 'markdown',
          required: true,
        }
      - { label: 'Treść', name: 'text', widget: 'markdown', required: true }
  - name: 'tips'
    label: 'Porady'
    folder: 'content/posts/tips'
    create: true
    fields:
      - { label: 'Tytuł podstrony', name: 'pageTitle', widget: 'string', required: true }
      - { label: 'Opis podstrony', name: 'pageDescription', widget: 'string', required: true }
      - { label: 'Tytuł porady', name: 'title', widget: 'string', required: true }
      - { label: 'Podtytuł porady', name: 'subtitle', widget: 'string', required: true }
      - { label: 'Data publikacji', name: 'date', widget: 'datetime', required: true }
      - {
          label: 'Obraz',
          name: 'featuredImage',
          widget: 'image',
          required: true,
          allowMultiple: false,
        }

      - {
          label: 'Kategorie',
          name: 'category',
          widget: 'relation',
          collection: 'category-tips',
          searchFields: ['title'],
          valueField: 'title',
        }
      - label: 'Spis treści'
        name: 'contents'
        widget: 'list'
        fields:
          - { label: 'Nazwa', name: 'name', widget: 'string', required: true }
          - { label: 'Odnośnik', name: 'link', widget: 'string', required: true }
      - label: 'Galeria zdjęć', 
        name: 'gallery', 
        widget: 'image', 
        allow_multiple: true, 
        media_library: 
          config:
            multiple: true 
      - {
          label: 'Wyróżniony nagłówek',
          name: 'highlightedText',
          widget: 'markdown',
          required: true,
        }
      - { label: 'Treść', name: 'text', widget: 'markdown', required: true }

  - name: 'ads'
    label: 'Ogłoszenia'
    folder: 'content/posts/ads'
    create: true
    fields:
      - { label: 'Tytuł podstrony', name: 'pageTitle', widget: 'string', required: true }
      - { label: 'Opis podstrony', name: 'pageDescription', widget: 'string', required: true }
      - { label: 'Tytuł ogłoszenia', name: 'title', widget: 'string', required: true }
      - { label: 'Podtytuł ogłoszenia', name: 'subtitle', widget: 'string', required: true }
      - { label: 'Data publikacji', name: 'date', widget: 'datetime', required: true }
      - {
          label: 'Obraz',
          name: 'featuredImage',
          widget: 'image',
          required: true,
          allowMultiple: false,
        }
      - label: 'Dane pojazdu'
        name: 'carData'
        widget: 'object'
        fields:
          - { label: 'Nazwa', name: 'name', widget: 'string', required: true }
          - { label: 'Miasto', name: 'localization', widget: 'string', required: true }
          - { label: 'Rok produkcji', name: 'year', widget: 'number', required: true }
          - { label: 'Nadwozie', name: 'body', widget: 'string', required: true }
          - { label: 'Silnik', name: 'engine', widget: 'string', required: true }
          - { label: 'Skrzynia biegów', name: 'gearbox', widget: 'string', required: true }
          - { label: 'Ilość koni mechanicznych', name: 'hp', widget: 'number', required: true }
          - { label: 'Moment obrotowy', name: 'torque', widget: 'number', required: true }
          - { label: 'Ilość drzwi', name: 'doors', widget: 'number', required: true }
          - { label: 'Przebieg', name: 'course', widget: 'number', required: true }
          - { label: 'Cena', name: 'price', widget: 'string', required: true }
      - label: 'Spis treści'
        name: 'contents'
        widget: 'list'
        fields:
          - { label: 'Nazwa', name: 'name', widget: 'string', required: true }
          - { label: 'Odnośnik', name: 'link', widget: 'string', required: true }
      - label: 'Galeria zdjęć', 
        name: 'gallery', 
        widget: 'image', 
        allow_multiple: true, 
        media_library: 
          config:
            multiple: true 
      - {
          label: 'Wyróżniony nagłówek',
          name: 'highlightedText',
          widget: 'markdown',
          required: true,
        }
      - { label: 'Treść', name: 'text', widget: 'markdown', required: true }
